# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
$:.unshift("../../lib")
require '../../lib/walt'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'Apple'

  app.pods do
    pod "AFNetworking"
  end
end
